module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    EMPLOYEE: 'EMPLOYEE'
  },
  ASSET_STATUS: {
    AVAILABLE: 'AVAILABLE',
    ALLOCATED: 'ALLOCATED',
    IN_MAINTENANCE: 'IN_MAINTENANCE',
    RETIRED: 'RETIRED',
    MISSING: 'MISSING'
  },
  REQUEST_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    COMPLETED: 'COMPLETED'
  },
  AUDIT_STATUS: {
    PASSED: 'PASSED',
    FAILED: 'FAILED',
    NEEDS_MAINTENANCE: 'NEEDS_MAINTENANCE',
    MISSING: 'MISSING'
  }
};
